// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqbaN9dfjS3BHBRpPkEKD131eCBVNsEgw',
    appId: '1:907084167150:web:f7ccd4e36432c83480c0ff',
    messagingSenderId: '907084167150',
    projectId: 'schoolmgmt-2025',
    authDomain: 'schoolmgmt-2025.firebaseapp.com',
    storageBucket: 'schoolmgmt-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhq2TC0OTDbcVLxLwE7yNO89P7Ch6YHtE',
    appId: '1:907084167150:android:647307ac5e5fb04b80c0ff',
    messagingSenderId: '907084167150',
    projectId: 'schoolmgmt-2025',
    storageBucket: 'schoolmgmt-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA62qvfGPJ0wniREonCfsEouT859AumBu0',
    appId: '1:907084167150:ios:cfef80ade2cddab380c0ff',
    messagingSenderId: '907084167150',
    projectId: 'schoolmgmt-2025',
    storageBucket: 'schoolmgmt-2025.firebasestorage.app',
    iosBundleId: 'com.example.schoolmgmt',
  );

}